import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import request from '../utils/request'


export default function Home({results}) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Cloning Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header title=''Home/>
    <Nav/>
    <Results results={results}/>
    </div>
  )
}
//data which rendered on a server
export async function getServerSideProps(context){
  const genre=context.query.genre;
  const required= await fetch(`https://api.themoviedb.org/3${
    request[genre]?.url || request.fetchTrending.url
  }`).then((res)=>res.json());
  return{
    props:{
      results:required.results,
    }
  }
}
